# Generated by Django 4.2.25 on 2025-10-22 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, help_text='TikTok post ID (19-digit numeric string)', max_length=50, unique=True)),
                ('title', models.TextField(help_text='Post caption/description', max_length=2200)),
                ('likes', models.IntegerField(help_text='Number of likes', validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(db_index=True, help_text='Post creation date')),
                ('cover_url', models.URLField(help_text='Cover/thumbnail image URL', max_length=500)),
                ('video_link', models.URLField(help_text='TikTok video URL', max_length=500)),
                ('views', models.IntegerField(blank=True, help_text='Number of views', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.IntegerField(blank=True, help_text='Number of comments', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('shares', models.IntegerField(blank=True, help_text='Number of shares', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.IntegerField(blank=True, help_text='Video duration in seconds', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('hashtags', models.JSONField(blank=True, default=list, help_text='Array of hashtags', null=True)),
                ('is_private', models.BooleanField(default=False, help_text='Whether the post is private')),
                ('is_pinned', models.BooleanField(default=False, help_text='Whether the post is pinned to profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TikTok Post',
                'verbose_name_plural': 'TikTok Posts',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='posts_post_date_d07427_idx'), models.Index(fields=['post_id'], name='posts_post_post_id_60d417_idx'), models.Index(fields=['-likes'], name='posts_post_likes_27dadd_idx')],
            },
        ),
    ]
