# Generated by Django 4.2.25 on 2025-10-23 20:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='TikTok username being followed', max_length=100)),
                ('date_followed', models.DateTimeField(db_index=True, help_text='Date when this user was followed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was imported')),
                ('user', models.ForeignKey(help_text='User account this following relationship belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Following',
                'verbose_name_plural': 'Following',
                'ordering': ['-date_followed'],
                'indexes': [models.Index(fields=['user', '-date_followed'], name='posts_follo_user_id_f4ed5c_idx'), models.Index(fields=['username'], name='posts_follo_usernam_f7e8a4_idx')],
                'unique_together': {('user', 'username')},
            },
        ),
        migrations.CreateModel(
            name='FollowerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(db_index=True, help_text='Date of this snapshot')),
                ('follower_count', models.IntegerField(help_text='Total number of followers at this date', validators=[django.core.validators.MinValueValidator(0)])),
                ('following_count', models.IntegerField(help_text='Total number of following at this date', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this snapshot was created')),
                ('user', models.ForeignKey(help_text='User account this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='follower_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follower Snapshot',
                'verbose_name_plural': 'Follower Snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user', '-snapshot_date'], name='posts_follo_user_id_cee149_idx')],
                'unique_together': {('user', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='TikTok username of the follower', max_length=100)),
                ('date_followed', models.DateTimeField(db_index=True, help_text='Date when this user started following')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was imported')),
                ('user', models.ForeignKey(help_text='User account this follower belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follower',
                'verbose_name_plural': 'Followers',
                'ordering': ['-date_followed'],
                'indexes': [models.Index(fields=['user', '-date_followed'], name='posts_follo_user_id_f2c058_idx'), models.Index(fields=['username'], name='posts_follo_usernam_0c71b6_idx')],
                'unique_together': {('user', 'username')},
            },
        ),
    ]
